const dummyData = [
    {
      id: 1,
      imageUrl: '/logos/mobilebanner.png',
      logoUrl: '/logos/download.png',
      name: 'FLEX ON Club 99',
      industry: 'Fitness et du bien-être',
      location: 'Ammara 2, Cheraga, Alger',
      since: 'Depuis 2022',
      jobOffers: '8 عروض شاغرة',
    },
    {
      id: 2,
      imageUrl: '/logos/levis.png',
      logoUrl: '/logos/download (1).png',
      name: 'Sample Company 2',
      industry: 'Technology',
      location: 'City Center, New York',
      since: '1000 to 2000 Employees',
      jobOffers: '8 عروض شاغرة',
    },
    {
      id: 3,
      imageUrl: '/logos/Inilah+Media+CNBC+Indonesia.png',
      logoUrl: '/logos/images.jpeg',
      name: 'Fitness Hub',
      industry: 'Health and Fitness',
      location: 'Gym Street, Los Angeles',
      since: '30 to 100 Employees',
      jobOffers: '2 عروض شاغرة',
    },
    {
      id: 4,
      imageUrl: '/logos/ford.png',
      logoUrl: '/logos/images (1).png',
      name: 'Tech Innovators',
      industry: 'Technology',
      location: 'Innovation Square, San Francisco',
      since: 'Since 2015',
      jobOffers: '10 عروض شاغرة',
    },
    {
      id: 5,
      imageUrl: '/logos/amazon.png',
      logoUrl: '/logos/png-transparent-logo-amazon-com-brand-flipkart-others-text-orange-logo-thumbnail.png',
      name: 'Green Earth',
      industry: 'Environmental Conservation',
      location: 'Eco Avenue, Seattle',
      since: 'Since 2008',
      jobOffers: 'لا توجد عروض',
    },
    {
      id: 6,
      imageUrl: '/logos/NIKE_BANNER.png',
      logoUrl: '/logos/images (2).png',
      name: 'Culinary Delights',
      industry: 'Food and Beverage',
      location: 'Taste Street, Paris',
      since: 'Since 2012',
      jobOffers: 'لا توجد عروض',
    },
    {
      id: 7,
      imageUrl: '/logos/HM-from-shutterstock.png',
      logoUrl: '/logos/images.png',
      name: 'Artistic Creations',
      industry: 'Arts and Design',
      location: 'Art Boulevard, Rome',
      since: 'Since 2007',
      jobOffers: '3 عروض شاغرة',
    },
    {
      id: 8,
      imageUrl: '/logos/twiiter.png',
      logoUrl: '/logos/t_twitter-x-icon3832.logowik.com.png',
      name: 'Global Connections',
      industry: 'International Business',
      location: 'Global Street, London',
      since: 'Since 2011',
      jobOffers: '20 عروض شاغرة',
    },
  ];
  
  export default dummyData;

  const Data = [
    {
      id: 1,
      image: "/logos/download.png",
      title: "Frontend Developer",
      time: "Yesterday",
      location: "United States",
      desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type",
      company: "TechWave Inc.",
    },
    {
      id: 2,
      image: "/logos/download (1).png",
      title: "Full Stack Engineer",
      time: "2 days ago",
      location: "Germany",
      desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type",
      company: "CodeFusion Solutions",
    },
    {
      id: 3,
      image: "/logos/images.png",
      title: "UX/UI Designer",
      time: "3 days ago",
      location: "Australia",
      desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type",
      company: "PixelCraft Studios",
    },
    {
      id: 4,
      image: "/logos/images.jpeg",
      title: "Data Scientist",
      time: "4 days ago",
      location: "India",
      desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type",
      company: "Data Insights Labs",
    },
    {
      id: 5,
      image: "/logos/images (1).png",
      title: "Product Manager",
      time: "5 days ago",
      location: "United Kingdom",
      desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type",
      company: "Innovation Innovators",
    },
    {
      id: 6,
      image: "/logos/images (2).png",
      title: "Software Engineer",
      time: "1 week ago",
      location: "Canada",
      desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type",
      company: "Binary Bytes",
    },
    {
      id: 7,
      image: "/logos/png-transparent-logo-amazon-com-brand-flipkart-others-text-orange-logo-thumbnail.png",
      title: "Backend Developer",
      time: "2 weeks ago",
      location: "France",
      desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type",
      company: "CodeNest Labs",
    },
    {
      id: 8,
      image: "/logos/t_twitter-x.png",
      title: 'Marketing Specialist',
      time: '3 weeks ago',
      location: 'Spain',
      desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type",
      company: 'BuzzBoost Marketing',
    },
  ];
  